on: push
name: Build, export and publish to build branch on push
jobs:
  build-export-and-deploy:
    name: Build, export and publish sample site to the `build` branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build with the latest action rev
        uses: tsg-iitkgp/next-build-export-action@v1.0
        env:
          BUILD_DIR: .
          PAGES_BRANCH: build
          TOKEN: ${{ secrets.TOKEN }}
