name: Build, export and publish to build branch on push
on:
  push:
    branches: [main]

jobs:
  build-export-and-deploy:
    name: Build, export and publish sample site to the `build` branch
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build with the latest action rev
        uses: tsg-iitkgp/next-build-export-action@v1.1
        env:
          BUILD_DIR: .
          PAGES_BRANCH: build
          TOKEN: ${{ secrets.TOKEN }}
